version: '3'
services:
  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"
    networks:
      - atomhabmnet

  db:
    image: postgres:16-alpine
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      retries: 5
      timeout: 3s
    networks:
      - atomhabmnet

  app:
    build: .
    tty: true
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c  "python manage.py migrate && python manage.py createusers && python manage.py seed && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - atomhabmnet

  celery:
    build: .
    tty: true
    env_file:
      - .env
    restart: on-failure
    command: sh -c  "celery -A config worker -l INFO"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app
    networks:
      - atomhabmnet

  celery-beat:
    build: .
    tty: true
    env_file:
      - .env
    restart: on-failure
    command: sh -c  "celery -A config worker --beat --scheduler django --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app
    networks:
      - atomhabmnet

volumes:
  pg_data:
networks:
  atomhabmnet:
    driver: bridge
